// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: hxalxhzoxstkjmsvoxzq

class SupabaseConfig {
  static const String supabaseUrl = 'https://hxalxhzoxstkjmsvoxzq.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4YWx4aHpveHN0a2ptc3ZveHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMDY0NDAsImV4cCI6MjA3Njg4MjQ0MH0.2ihQT8QrZVqBHc1tiWeUWec19hUXz5tTTyz8SGnmAv4';
}
